### ISSUE TITLE
Module issue?

### ISSUE THREAD

**Issue by WebBreacher** [yamakira/spaces-finder#1]
When I run this on a Python 2.7 box, It gives me the following error:

$  python spaces_finder.py
Traceback (most recent call last):
  File "spaces_finder.py", line 22, in <module>
    from queue import Queue
ImportError: No module named queue

Changing line 22 to be "from Queue import Queue" instead of "from queue import Queue" fixes it. (notice the lowercase q)

Submitting this as an issue instead of a PR since it may not impact everyone.

**Comment by WebBreacher** [comment]
that is it. in python3 the module is "queue" and python2.x it is "Queue". Feel free to address or close.

**Comment by 0xbharath** [comment]
Yes. This tool is supposed to be run using Python 3.
